### ISSUE TITLE
muitl thread query,and cause error

### ISSUE THREAD

**Issue by edidada** [rbock/sqlpp11#589]
```
 sqlpp::normal_connection<sqlpp::mysql::connection_base>& conn = *ptr;
        // 现在您可以使用 conn 来执行数据库操作
        auto result = conn(sqlpp::select(userTbl.id, userTbl.name, userTbl.age).from(userTbl).unconditionally());
        for (const auto& row : result) {
            users.emplace_back(row.id, row.name, row.age);
        }
```
error:

```shell
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139659361121856)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139659361121856)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139659361121856, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f04faa05476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f04fa9eb7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005629ba805ee6 in OPENSSL_die (message=0x5629bae80022 "refcount error", 
    file=0x5629bae7ffd8 "ssl/ssl_lib.c", line=1412) at crypto/cryptlib.c:260
#6  0x00005629ba6b6277 in SSL_free (s=0x5629bbb54fa0) at ssl/ssl_lib.c:1412
#7  0x00005629ba0c355a in vio_ssl_delete (vio=0x5629bbb50960)
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/vio/viossl.cc:395
#8  0x00005629ba079c21 in end_server (mysql=0x5629bbb50200)
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/sql-common/client.cc:1902
#9  0x00005629ba077dde in cli_advanced_command (mysql=0x5629bbb50200, 
    command=COM_QUERY, header=0x0, header_length=0, 
    arg=0x7f04ec0020b0 "SELECT users.id,users.name,users.age FROM users", 
    arg_length=47, skip_check=true, stmt=0x0)
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/sql-common/client.cc:1408
#10 0x00005629ba08cd2a in mysql_send_query (mysql=0x5629bbb50200, 
    query=0x7f04ec0020b0 "SELECT users.id,users.name,users.age FROM users", length=47)
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/sql-common/client.cc:7950
#11 0x00005629ba08d36b in mysql_real_query (mysql=0x5629bbb50200, 
    query=0x7f04ec0020b0 "SELECT users.id,users.name,users.age FROM users", length=47)
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/sql-common/client.cc:8063
#12 0x00005629ba06b76e in mysql_query (mysql=0x5629bbb50200, 
    query=0x7f04ec0020b0 "SELECT users.id,users.name,users.age FROM users")
    at /home/wdidada/.conan2/p/b/libmy7ac110d9d417d/b/src/libmysql/libmysql.cc:663
#13 0x00005629b9faa7dd in sqlpp::mysql::detail::execute_statement (
    handle=std::unique_ptr<sqlpp::mysql::detail::connection_handle> = {...}, 
    statement="SELECT users.id,users.name,users.age FROM users")
```

**Comment by rbock** [comment]
This does not nearly contain enough information. The code you show should work. The bug is elsewhere.

I am closing this as invalid.

Please reduce the problem to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

I suspect that while you do so, you will find the bug. If not, please open a *new* issue.

**Comment by rbock** [comment]
You may want to read this, too: https://github.com/rbock/sqlpp11/blob/main/docs/Threads.md
